In [1]:
import numpy as np

# Numpy Basics

In [2]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [3]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Get Dimension and shape

In [4]:
a.ndim

1

In [5]:
b.shape

(2, 5)

### Size

In [6]:
print(a.itemsize)
print(a.dtype)

# here size will be 4, coz by default dtype is int32, so 32/8 = 4

4
int32


### changing dtype

In [7]:
c = np.array([1, 2, 3, 4, 5], dtype='int16')
print(c.itemsize)

# here item size will be 2, coz 16/8 = 2, 
# Remember that, c.size returns the length of the array and c.itemsize returns the actual size in bytes

print(c.size)
#or
print(np.size(c))

2
5
5


### Get total size

In [8]:
# total size can be calculated as (total no items * itemsize),

print(c.size * c.itemsize)
#or
print(c.nbytes)

10
10


### Accessing/Changing specific rows, column, etc

In [9]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# get a specific element [r, c]
print(arr[1, 2])

10


In [11]:
# get a specific row
print(arr[0, :])

# using : prints every element in that rowb

[1 2 3 4 5 6 7]


In [12]:
# get a specific column
print(arr[:, 3])

[ 4 11]


In [13]:
# [startindex:endindex:stepsize]
print(arr[0, 1:-1:2])

[2 4 6]


In [14]:
# changing an element
arr[0, 3] = 23
print(arr)


# changing a particular column
arr[:, 2] = 3
print(arr)
# or
arr[:, 2] = [13, 14]
print(arr)


# changing a particular row
arr[1, :] = 17
print(arr)
# or
arr[1, :] = [21, 22, 23, 24, 25, 26, 27]
print(arr)

[[ 1  2  3 23  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3 23  5  6  7]
 [ 8  9  3 11 12 13 14]]
[[ 1  2 13 23  5  6  7]
 [ 8  9 14 11 12 13 14]]
[[ 1  2 13 23  5  6  7]
 [17 17 17 17 17 17 17]]
[[ 1  2 13 23  5  6  7]
 [21 22 23 24 25 26 27]]


### 3d example

In [15]:
# creating a 3d array
arr2 = np.array([ [[1,2], [3,4]], [[5,6], [7,8]] ])
print(arr2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
# accessing an element
print(arr2[0, 1, 1])
arr2[:, 0, :]

4


array([[1, 2],
       [5, 6]])

In [25]:
# replace
arr2[:, 1, :] = [[9, 9], [8, 8]]

In [26]:
arr2

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing different Types of Arrays

In [27]:
# All 0's matrix
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
# All 1's matrix
np.ones((5,4), dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
# Any other number
np.full((4,8), 65)

array([[65, 65, 65, 65, 65, 65, 65, 65],
       [65, 65, 65, 65, 65, 65, 65, 65],
       [65, 65, 65, 65, 65, 65, 65, 65],
       [65, 65, 65, 65, 65, 65, 65, 65]])

In [36]:
# Any other number(full_like)
np.full_like(arr2, 4)

# it takes shapes of a already predefined array, here it is arr2



array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [77]:
# Random Decimal Numbers
t = np.random.rand(2, 4)
print(t)

print('--------------')
# passing a shape
t1 = np.random.random_sample(arr2.shape)
print(t1)

[[0.62536639 0.85555959 0.58174906 0.50477783]
 [0.36033425 0.15781284 0.29517916 0.42148633]]
--------------
[[[0.71642649 0.94253914]
  [0.56495566 0.32694453]]

 [[0.67240476 0.40508843]
  [0.01018926 0.79127766]]]


In [72]:
# Random Integer values
np.random.randint(30, size= (2,4))

# 1st argument is maximum value, and 2nd is size

# or (with startindex and endindex)
arr4 = np.random.randint(-8, 8, size=(3, 3))  # here 8 is exclusive
print(arr4)

[[-7  5  7]
 [-3  0 -7]
 [ 2 -5  5]]


In [84]:
# Identity Matrix
np.identity(8)


array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [137]:
# Repeat an array
arr = np.array([1, 2, 3, 4])
rep = np.repeat(arr, 3)
print(rep)

## on 2d array
arr = np.array([[1, 2, 3]])
res = np.repeat(arr, 3, axis=0)
print(res)

[1 1 1 2 2 2 3 3 3 4 4 4]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Question:- Print this Array 👇

![](ques1.png)


In [155]:
# Solution
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:4, 1:4] = z
print(output)
#or
output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


   # 💀Be Careful while copying Arrays!!!💀

### Context👇👇

In [158]:
a = np.array([1, 2, 3])
b = a
# here b array is just pointing to a, it is not copied
b[1] = 65
# value of a is also getting changed
print(a)

# To prevent this we will use .copy() method
c = np.array([1, 2, 3])
d = c.copy()
d[1] = 45
print(c)
print(d)

[ 1 65  3]
[1 2 3]
[ 1 45  3]


### Mathematics

In [159]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [161]:
a + 2

array([3, 4, 5, 6])

In [162]:
a - 2

array([-1,  0,  1,  2])

In [163]:
a * 2

array([2, 4, 6, 8])

In [164]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [165]:
a ** 2

array([ 1,  4,  9, 16])

In [166]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [167]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [168]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [169]:
# For more visit this :- (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

#### Linear Algebra

In [171]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

# Matrix Multiplication
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [173]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [178]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [179]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [180]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Bonus 💙🔥

### Load Data from a File

In [182]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[ 88  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5  41   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76 100]]


### Boolean Masking and Advanced Indexing

In [183]:
filedata > 60

array([[ True, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [185]:
# using index
filedata[filedata > 50]

array([ 88, 196,  75, 766,  75,  55, 999,  78,  76, 100])

In [193]:
np.any(filedata > 50, axis=0)

array([ True, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [195]:
(((filedata > 50) & (filedata < 100)))

array([[ True, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True, False]])

In [197]:
# ~ means negation
(~((filedata > 50) & (filedata < 100)))

array([[False,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False,  True]])